### ISSUE TITLE
Missing pre-trained model

### ISSUE THREAD

**Issue by iqbalnaved** [guozhongluo/head-pose-estimation-and-face-landmark#2]
Hi 

The baidu page containing link for the pretrained model does not exist anymore. Could you pleas share the link here ? 

Thanks.

**Comment by iqbalnaved** [comment]
Sorry the page is working now.

**Comment by guozhongluo** [comment]
https://www.dropbox.com/s/z89prwhg0jpgp47/68point_dlib_with_pose.caffemodel?dl=0

**Comment by guozhongluo** [comment]
@iqbalnaved https://www.dropbox.com/s/z89prwhg0jpgp47/68point_dlib_with_pose.caffemodel?dl=0
