### ISSUE TITLE
About the yaw,pitch,roll

### ISSUE THREAD

**Issue by asdfghwunai** [guozhongluo/head-pose-estimation-and-face-landmark#4]
Hello,can you tell me how you get the yaw,pitch and roll's data?I didn't find them in 300-W data set.

**Comment by guozhongluo** [comment]
Using the [openface](https://github.com/TadasBaltrusaitis/OpenFace) library to calculate yaw pitch,roll

**Comment by xizi** [comment]
Hi, guozhong, are you use openface library calculate 300-W data set's euler angles according to it's landmark and train the network?
