### ISSUE TITLE
face landmark问题相当于多标签回归？

### ISSUE THREAD

**Issue by liuqunzhong** [guozhongluo/head-pose-estimation-and-face-landmark#5]
caffe
分类问题的时候 标签都是整数，像训练人脸识别模型那样。
如果做回归的时候，把数值归一化到-1,1或者0,1之间，那标签相当于是小数？
caffe的convert_imageset接口好像不能读小数标签啊 要改？

**Comment by guozhongluo** [comment]
Hdf5格式输入就支持0～1

**Comment by liuqunzhong** [comment]
谢谢  刚搞懂caffe怎么做回归问题。
这个网络的体积有点大啊
有没有又快又好的结构呢？
mtcnn里面的第三层结构很简单，为何点找的比其他算法要好，跟人脸框回归有关系？

**Comment by liuqunzhong** [comment]
又快又好又小

**Comment by guozhongluo** [comment]
@liuqunzhong

mtcnn的回归很简单，好是因为算法经过stage1,stage2网络的box回归，box位置比较好，另外Onet训练的时候经过finetune训练，对相近的数据分布有较好的效果。

又快又好又小网络需要自己设计，达到vgg同等精度，可以做到1M以下，看你功力了
