### ISSUE TITLE
哪里可以下载300w data set呢？

### ISSUE THREAD

**Issue by RenXiandong888** [guozhongluo/head-pose-estimation-and-face-landmark#7]
请问哪儿可以下载300w data set？

**Comment by guozhongluo** [comment]
[(https://ibug.doc.ic.ac.uk/resources/300-W/)]

**Comment by guozhongluo** [comment]
[300W](https://ibug.doc.ic.ac.uk/resources/300-W/)

**Comment by RenXiandong888** [comment]
非常感谢，但是这个数据集里只有68landmark的标签，貌似没有head-pose的数据集，还是说我看漏了什么？

**Comment by guozhongluo** [comment]
是没有head-pose数据集，head pose 是用openface算出来的，地址：https://github.com/TadasBaltrusaitis/OpenFace <https://github.com/TadasBaltrusaitis/OpenFace>
